accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleApp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleApp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleApp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

djangoStartProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleApp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleApp.urls')),
    path('comments/', include('commentApp.urls')),
    path('projects/', include('projectApp.urls')),
    path('subscribe/', include('subscribeApp.urls')),
    path('likes/', include('likeApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likeApp/urls.py
from django.urls import path

from likeApp.views import LikeArticleView

app_name = 'likeApp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

projectApp/urls.py
from django.urls import path

from projectApp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectApp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),

    path('list/', ProjectListView.as_view(), name='list'),
]

subscribeApp/urls.py
from django.urls import path

from subscribeApp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeApp'

urlpatterns = [
    path('subscribe/<int:project_pk>', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<body style="font-family: 'NanumSquareR'">
{% include 'header.html' %}

<hr>

{% for message in messages %}
    <div class="text-center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5">
            {{ message }}
        </div>
    </div>
{% endfor %}

{% block content %}
{% endblock %}

<hr>

{% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div style="text-align: center;">
    <div class="footer_buttons">
        <span>button1</span>
        <span>button2</span>
        <span>button3</span>
    </div>
    <div class="footer_logo">
        <h5>Django Start Project</h5>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Title</title>
    {#  Bootstrap Link  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
    >

    {#  Google Fonts Link  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">

    {#  Static Files Link  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {#  MATERIAL ICONS LINK  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div style="text-align: center;">
    <div class="header_logo">
        <h1>
            <a href="{% url 'home' %}">
                Django Start Project
            </a>
        </h1>
    </div>
    <div class="header_buttons">
        <span class="mx-2">
            <a href="{% url 'articleApp:list' %}">
                Articles
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'projectApp:list' %}">
                Projects
            </a>
        </span>
        {% if user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'subscribeApp:list' %}">
                Subscription
            </a>
        </span>
        {% endif %}
        {% if not user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'accounts:login' %}">
                Login
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'accounts:create' %}">
                SignUp
            </a>
        </span>
        {% else %}
        <span class="mx-2">
            <a href="{% url 'accounts:logout' %}">
                Logout
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'accounts:detail' pk=user.pk %}">
                MyPage
            </a>
        </span>
        {% endif %}
    </div>
</div>